// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATzjB9YG6fGFckHt8xEshQvHxHZ3RGx2g',
    appId: '1:140380734440:web:d51c68c77aa9cf8ed81a5d',
    messagingSenderId: '140380734440',
    projectId: 'carbon-tracker-6686b',
    authDomain: 'carbon-tracker-6686b.firebaseapp.com',
    storageBucket: 'carbon-tracker-6686b.firebasestorage.app',
    measurementId: 'G-DR5XC5J1WK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDa5u8Ohd4leeZW5zHDY-GvHRfhoIsdk6s',
    appId: '1:140380734440:android:f9f24f4d1d3e0d47d81a5d',
    messagingSenderId: '140380734440',
    projectId: 'carbon-tracker-6686b',
    storageBucket: 'carbon-tracker-6686b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0tbdS3wU1AfYtt3Si0B0BdppU89o0vPI',
    appId: '1:140380734440:ios:50760b5bf9b208d7d81a5d',
    messagingSenderId: '140380734440',
    projectId: 'carbon-tracker-6686b',
    storageBucket: 'carbon-tracker-6686b.firebasestorage.app',
    iosBundleId: 'com.wenting.carbonTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0tbdS3wU1AfYtt3Si0B0BdppU89o0vPI',
    appId: '1:140380734440:ios:5768b78f3c28c573d81a5d',
    messagingSenderId: '140380734440',
    projectId: 'carbon-tracker-6686b',
    storageBucket: 'carbon-tracker-6686b.firebasestorage.app',
    iosBundleId: 'com.Ling.carbonTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATzjB9YG6fGFckHt8xEshQvHxHZ3RGx2g',
    appId: '1:140380734440:web:194b90974a23a484d81a5d',
    messagingSenderId: '140380734440',
    projectId: 'carbon-tracker-6686b',
    authDomain: 'carbon-tracker-6686b.firebaseapp.com',
    storageBucket: 'carbon-tracker-6686b.firebasestorage.app',
    measurementId: 'G-N7GFVLJSDR',
  );
}
